Feature/main event squadscore
story-squad/contest-deno-be pull request #52
Opened 2021-04-21 20:49 UTC by VPDeb

Created Main.py for Squad Score for Classroom Rumble app.

2021-04-21 23:38 UTC, lorischl-otter requested changes
Thanks for getting this uploaded. I added in a few change requests. 

Also, looks like you're already on top of this for the next push, but if you can get rid of the .ipynb_checkpoints & the second `fdbkassign` notebook, that would be great. Also, unless @bramirez96 has a different preference, if you can keep the changes on these files in one PR, that would be helpful to track what you're changing each time. You can just push any new changes from this PR to the same branch, and it will update here. 

Let me know if you have any Qs!

2021-04-21 23:38 UTC, lorischl-otter commented on scripts/process_submission/main.py
> +{maybe boto3}
This line should be removed -- it was just part of my transfer notes :)

2021-04-21 23:38 UTC, lorischl-otter commented on scripts/process_submission/main.py
> +    for page_num in sub.Pages: (maybe not for loop if only 1 page):
This parenthetical `(maybe not...)` should also be removed. @bramirez96 can you confirm whether Classroom Rumble can have multiple page submissions? Or just single page? If just single page, we could remove this from a for loop if we want to.

2021-04-21 23:38 UTC, lorischl-otter commented on scripts/process_submission/main.py
> +                # fetch file from s3 bucket
Looks like there are some remaining tabbing issues from my Slack message -- looks like the code might be alright, but a few of the comments here look a little misaligned.

2021-04-21 23:38 UTC, lorischl-otter commented on scripts/process_submission/main.py
> +    # change this ??
This comment can be removed

2021-04-22 21:50 UTC, bramirez96 commented on scripts/process_submission/main.py
> +    for page_num in sub.Pages: (maybe not for loop if only 1 page):
Just single page for now!

2021-04-22 21:51 UTC, bramirez96 commented
I agree, clean the code up, and let's get it all into one PR. There are currently 3 open and I think they're all your branches.

2021-04-22 21:53 UTC, bramirez96 commented
Also, make SURE to switch the branch from `main` to `development`. Click on `Edit` next to your PR title to change it.

2021-05-19 17:35 UTC, closed without merging